[tool.poetry]
name = "tog"
version = "0.1.0"
description = "Command line tool for interacting with tog data server"
authors = []
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.4.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
